"""empty message

Revision ID: db7c27ff7144
Revises: e27696b3c5f5
Create Date: 2018-08-09 08:44:49.979721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7c27ff7144'
down_revision = 'e27696b3c5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('ubusoAhingahoIbindi', sa.String(length=200), nullable=True))
    op.add_column('members', sa.Column('ubusoBudakoreshwa', sa.String(length=200), nullable=True))
    op.add_column('members', sa.Column('ubwokoBwigihingwaKindi', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'ubwokoBwigihingwaKindi')
    op.drop_column('members', 'ubusoBudakoreshwa')
    op.drop_column('members', 'ubusoAhingahoIbindi')
    # ### end Alembic commands ###
