"""empty message

Revision ID: decdaa95cde0
Revises: 
Create Date: 2018-06-15 10:47:02.019488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'decdaa95cde0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sno', sa.String(length=300), nullable=True),
    sa.Column('code', sa.String(length=300), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('certificate', sa.String(length=300), nullable=True),
    sa.Column('reg_date', sa.String(length=300), nullable=True),
    sa.Column('province', sa.String(length=300), nullable=True),
    sa.Column('district', sa.String(length=300), nullable=True),
    sa.Column('sector', sa.String(length=300), nullable=True),
    sa.Column('activity', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('amount', sa.String(length=300), nullable=True),
    sa.Column('date', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('userinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=300), nullable=True),
    sa.Column('secondname', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applytrainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namea', sa.String(length=300), nullable=True),
    sa.Column('abouta', sa.String(length=300), nullable=True),
    sa.Column('descriptiona', sa.String(length=300), nullable=True),
    sa.Column('datea', sa.String(length=300), nullable=True),
    sa.Column('is_activea', sa.Boolean(), nullable=True),
    sa.Column('department_id', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('Description', sa.String(length=300), nullable=True),
    sa.Column('Amount', sa.String(length=300), nullable=True),
    sa.Column('startingDate', sa.String(length=300), nullable=True),
    sa.Column('endingDate', sa.String(length=300), nullable=True),
    sa.Column('paidMembers', sa.String(length=300), nullable=True),
    sa.Column('department_id', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ibitabobyabanks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no', sa.String(length=300), nullable=True),
    sa.Column('date', sa.String(length=300), nullable=True),
    sa.Column('igikorwa', sa.String(length=300), nullable=True),
    sa.Column('debit', sa.String(length=300), nullable=True),
    sa.Column('credit', sa.String(length=300), nullable=True),
    sa.Column('solde', sa.String(length=300), nullable=True),
    sa.Column('department_id', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('inamaubuyobozi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=300), nullable=True),
    sa.Column('decision', sa.String(length=300), nullable=True),
    sa.Column('owner', sa.String(length=300), nullable=True),
    sa.Column('stakeholders', sa.String(length=300), nullable=True),
    sa.Column('due_date', sa.String(length=300), nullable=True),
    sa.Column('background', sa.String(length=300), nullable=True),
    sa.Column('department_id', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('intekorusange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status1', sa.String(length=300), nullable=True),
    sa.Column('decision1', sa.String(length=300), nullable=True),
    sa.Column('owner1', sa.String(length=300), nullable=True),
    sa.Column('stakeholders1', sa.String(length=300), nullable=True),
    sa.Column('due_date1', sa.String(length=300), nullable=True),
    sa.Column('background1', sa.String(length=300), nullable=True),
    sa.Column('department_id', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('isanduku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no', sa.String(length=300), nullable=True),
    sa.Column('done_date', sa.String(length=300), nullable=True),
    sa.Column('action', sa.String(length=300), nullable=True),
    sa.Column('income', sa.String(length=300), nullable=True),
    sa.Column('expense', sa.String(length=300), nullable=True),
    sa.Column('remain', sa.String(length=300), nullable=True),
    sa.Column('done_by', sa.String(length=300), nullable=True),
    sa.Column('done_to', sa.String(length=300), nullable=True),
    sa.Column('department_id', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('trainer', sa.String(length=300), nullable=True),
    sa.Column('about', sa.String(length=300), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('date', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('department_id', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ubugenzuzi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=300), nullable=True),
    sa.Column('decision', sa.String(length=300), nullable=True),
    sa.Column('owner', sa.String(length=300), nullable=True),
    sa.Column('stakeholders', sa.String(length=300), nullable=True),
    sa.Column('due_date', sa.String(length=300), nullable=True),
    sa.Column('background', sa.String(length=300), nullable=True),
    sa.Column('department_id', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('umusaruro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Amazina', sa.String(length=300), nullable=True),
    sa.Column('Taliki', sa.String(length=300), nullable=True),
    sa.Column('Uwagemuye', sa.String(length=300), nullable=True),
    sa.Column('Ibiro', sa.String(length=300), nullable=True),
    sa.Column('Igiciro', sa.String(length=300), nullable=True),
    sa.Column('IkiguziCyose', sa.String(length=300), nullable=True),
    sa.Column('amafarangaYishyuweKuKiro', sa.String(length=300), nullable=True),
    sa.Column('done_by', sa.String(length=300), nullable=True),
    sa.Column('done_to', sa.String(length=300), nullable=True),
    sa.Column('on_market', sa.Boolean(), nullable=True),
    sa.Column('department_id', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('unions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sno', sa.String(length=300), nullable=True),
    sa.Column('code', sa.String(length=300), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('certificate', sa.String(length=300), nullable=True),
    sa.Column('reg_date', sa.String(length=300), nullable=True),
    sa.Column('province', sa.String(length=300), nullable=True),
    sa.Column('district', sa.String(length=300), nullable=True),
    sa.Column('sector', sa.String(length=300), nullable=True),
    sa.Column('activity', sa.String(length=300), nullable=True),
    sa.Column('federation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('plate', sa.String(length=300), nullable=True),
    sa.Column('owner', sa.String(length=300), nullable=True),
    sa.Column('owner_tel', sa.String(length=300), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('userInfo')
    op.add_column(u'applications', sa.Column('Amashuriaa', sa.String(length=300), nullable=True))
    op.add_column(u'applications', sa.Column('Cellaa', sa.String(length=300), nullable=True))
    op.add_column(u'applications', sa.Column('Districtaa', sa.String(length=300), nullable=True))
    op.add_column(u'applications', sa.Column('Sectoraa', sa.String(length=300), nullable=True))
    op.add_column(u'applications', sa.Column('Ubumugaaa', sa.String(length=300), nullable=True))
    op.add_column(u'applications', sa.Column('dobaa', sa.String(length=300), nullable=True))
    op.add_column(u'applications', sa.Column('emailaa', sa.String(length=300), nullable=True))
    op.add_column(u'applications', sa.Column('entryDateaa', sa.String(length=300), nullable=True))
    op.add_column(u'applications', sa.Column('exitDateaa', sa.String(length=300), nullable=True))
    op.add_column(u'applications', sa.Column('firstNameaa', sa.String(length=300), nullable=True))
    op.add_column(u'applications', sa.Column('genderaa', sa.String(length=300), nullable=True))
    op.add_column(u'applications', sa.Column('nIdaa', sa.String(length=300), nullable=True))
    op.add_column(u'applications', sa.Column('othersaa', sa.String(length=300), nullable=True))
    op.add_column(u'applications', sa.Column('phoneaa', sa.String(length=300), nullable=True))
    op.add_column(u'applications', sa.Column('secondNameaa', sa.String(length=300), nullable=True))
    op.add_column(u'applications', sa.Column('shareaa', sa.String(length=300), nullable=True))
    op.add_column(u'applications', sa.Column('umukonoaa', sa.String(length=300), nullable=True))
    op.add_column(u'applications', sa.Column('umuzunguraaa', sa.String(length=300), nullable=True))
    op.create_unique_constraint(None, 'applications', ['id'])
    op.drop_column(u'applications', 'phone_number')
    op.drop_column(u'applications', 'first_name')
    op.drop_column(u'applications', 'last_name')
    op.drop_column(u'applications', 'district')
    op.drop_column(u'applications', 'gender')
    op.drop_column(u'applications', 'department_name')
    op.drop_column(u'applications', 'others')
    op.drop_column(u'applications', 'email')
    op.drop_column(u'applications', 'occupation')
    op.add_column(u'departments', sa.Column('cell', sa.String(length=300), nullable=True))
    op.add_column(u'departments', sa.Column('field', sa.String(length=300), nullable=True))
    op.add_column(u'departments', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column(u'departments', sa.Column('starting_share', sa.Integer(), nullable=True))
    op.add_column(u'employees', sa.Column('is_confederation', sa.Boolean(), nullable=True))
    op.add_column(u'employees', sa.Column('is_ferwacotamo', sa.Boolean(), nullable=True))
    op.add_column(u'employees', sa.Column('is_rca', sa.Boolean(), nullable=True))
    op.alter_column(u'employees', 'is_union',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.add_column(u'members', sa.Column('Amashuri', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('Cell', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('District', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('Language', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('Province', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('Sector', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('Ubumuga', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('age', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('dob', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('entryDate', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('exitDate', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('gender', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('has_children', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('insurance', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column(u'members', sa.Column('job', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('marital_status', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('member_source', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('rular_or_urban', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('share', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('ubudehe', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('umukono', sa.String(length=300), nullable=True))
    op.add_column(u'members', sa.Column('umuzungura', sa.String(length=300), nullable=True))
    op.drop_column(u'members', 'ownerTel')
    op.drop_column(u'members', 'dL')
    op.drop_column(u'members', 'resCell')
    op.drop_column(u'members', 'transportAutor')
    op.drop_column(u'members', 'resDistrict')
    op.drop_column(u'members', 'plateNo')
    op.drop_column(u'members', 'chassisNo')
    op.drop_column(u'members', 'cooperative')
    op.drop_column(u'members', 'parking')
    op.drop_column(u'members', 'owner')
    op.drop_column(u'members', 'engenNo')
    op.add_column(u'reports', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column(u'reports', sa.Column('notes', sa.String(length=200), nullable=True))
    op.add_column(u'reports', sa.Column('project', sa.String(length=200), nullable=True))
    op.add_column(u'reports', sa.Column('task', sa.String(length=200), nullable=True))
    op.drop_column(u'reports', 'owner')
    op.drop_column(u'reports', 'stakeholders')
    op.drop_column(u'reports', 'created_date')
    op.drop_column(u'reports', 'report_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'reports', sa.Column('report_name', mysql.VARCHAR(length=300), nullable=True))
    op.add_column(u'reports', sa.Column('created_date', mysql.VARCHAR(length=300), nullable=True))
    op.add_column(u'reports', sa.Column('stakeholders', mysql.VARCHAR(length=300), nullable=True))
    op.add_column(u'reports', sa.Column('owner', mysql.VARCHAR(length=300), nullable=True))
    op.drop_column(u'reports', 'task')
    op.drop_column(u'reports', 'project')
    op.drop_column(u'reports', 'notes')
    op.drop_column(u'reports', 'date')
    op.add_column(u'members', sa.Column('engenNo', mysql.VARCHAR(length=300), nullable=True))
    op.add_column(u'members', sa.Column('owner', mysql.VARCHAR(length=300), nullable=True))
    op.add_column(u'members', sa.Column('parking', mysql.VARCHAR(length=300), nullable=True))
    op.add_column(u'members', sa.Column('cooperative', mysql.VARCHAR(length=300), nullable=True))
    op.add_column(u'members', sa.Column('chassisNo', mysql.VARCHAR(length=300), nullable=True))
    op.add_column(u'members', sa.Column('plateNo', mysql.VARCHAR(length=300), nullable=True))
    op.add_column(u'members', sa.Column('resDistrict', mysql.VARCHAR(length=300), nullable=True))
    op.add_column(u'members', sa.Column('transportAutor', mysql.VARCHAR(length=300), nullable=True))
    op.add_column(u'members', sa.Column('resCell', mysql.VARCHAR(length=300), nullable=True))
    op.add_column(u'members', sa.Column('dL', mysql.VARCHAR(length=300), nullable=True))
    op.add_column(u'members', sa.Column('ownerTel', mysql.VARCHAR(length=300), nullable=True))
    op.drop_column(u'members', 'umuzungura')
    op.drop_column(u'members', 'umukono')
    op.drop_column(u'members', 'ubudehe')
    op.drop_column(u'members', 'share')
    op.drop_column(u'members', 'rular_or_urban')
    op.drop_column(u'members', 'member_source')
    op.drop_column(u'members', 'marital_status')
    op.drop_column(u'members', 'job')
    op.drop_column(u'members', 'is_active')
    op.drop_column(u'members', 'insurance')
    op.drop_column(u'members', 'has_children')
    op.drop_column(u'members', 'gender')
    op.drop_column(u'members', 'exitDate')
    op.drop_column(u'members', 'entryDate')
    op.drop_column(u'members', 'dob')
    op.drop_column(u'members', 'age')
    op.drop_column(u'members', 'Ubumuga')
    op.drop_column(u'members', 'Sector')
    op.drop_column(u'members', 'Province')
    op.drop_column(u'members', 'Language')
    op.drop_column(u'members', 'District')
    op.drop_column(u'members', 'Cell')
    op.drop_column(u'members', 'Amashuri')
    op.alter_column(u'employees', 'is_union',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column(u'employees', 'is_rca')
    op.drop_column(u'employees', 'is_ferwacotamo')
    op.drop_column(u'employees', 'is_confederation')
    op.drop_column(u'departments', 'starting_share')
    op.drop_column(u'departments', 'is_active')
    op.drop_column(u'departments', 'field')
    op.drop_column(u'departments', 'cell')
    op.add_column(u'applications', sa.Column('occupation', mysql.VARCHAR(length=3000), nullable=True))
    op.add_column(u'applications', sa.Column('email', mysql.VARCHAR(length=300), nullable=True))
    op.add_column(u'applications', sa.Column('others', mysql.VARCHAR(length=400), nullable=True))
    op.add_column(u'applications', sa.Column('department_name', mysql.VARCHAR(length=400), nullable=True))
    op.add_column(u'applications', sa.Column('gender', mysql.VARCHAR(length=4000), nullable=True))
    op.add_column(u'applications', sa.Column('district', mysql.VARCHAR(length=2000), nullable=True))
    op.add_column(u'applications', sa.Column('last_name', mysql.VARCHAR(length=400), nullable=True))
    op.add_column(u'applications', sa.Column('first_name', mysql.VARCHAR(length=400), nullable=True))
    op.add_column(u'applications', sa.Column('phone_number', mysql.VARCHAR(length=5000), nullable=True))
    op.drop_constraint(None, 'applications', type_='unique')
    op.drop_column(u'applications', 'umuzunguraaa')
    op.drop_column(u'applications', 'umukonoaa')
    op.drop_column(u'applications', 'shareaa')
    op.drop_column(u'applications', 'secondNameaa')
    op.drop_column(u'applications', 'phoneaa')
    op.drop_column(u'applications', 'othersaa')
    op.drop_column(u'applications', 'nIdaa')
    op.drop_column(u'applications', 'genderaa')
    op.drop_column(u'applications', 'firstNameaa')
    op.drop_column(u'applications', 'exitDateaa')
    op.drop_column(u'applications', 'entryDateaa')
    op.drop_column(u'applications', 'emailaa')
    op.drop_column(u'applications', 'dobaa')
    op.drop_column(u'applications', 'Ubumugaaa')
    op.drop_column(u'applications', 'Sectoraa')
    op.drop_column(u'applications', 'Districtaa')
    op.drop_column(u'applications', 'Cellaa')
    op.drop_column(u'applications', 'Amashuriaa')
    op.create_table('userInfo',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('secondname', mysql.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('motos')
    op.drop_table('unions')
    op.drop_table('umusaruro')
    op.drop_table('ubugenzuzi')
    op.drop_table('trainings')
    op.drop_table('isanduku')
    op.drop_table('intekorusange')
    op.drop_table('inamaubuyobozi')
    op.drop_table('ibitabobyabanks')
    op.drop_table('goals')
    op.drop_table('applytrainings')
    op.drop_table('userinfo')
    op.drop_table('payments')
    op.drop_table('federations')
    # ### end Alembic commands ###
